// Prints (and writes docs/DATA_REVIEW.md) a checklist of calculator figures that
// still need a human to verify them against the primary document.
// Usage: npm run data:review
import { readFile, writeFile, mkdir } from "node:fs/promises";

const load = async (p) =>
  JSON.parse(await readFile(new URL(`../src/content/${p}`, import.meta.url)));
const [budget, assumptions, tax, provinces, pitch] = await Promise.all(
  ["budget.json", "assumptions.json", "tax.json", "provinces.json", "pitch.json"].map(load),
);

const scenarioDir = new URL("../src/content/scenarios/", import.meta.url);
const { readdir } = await import("node:fs/promises");
const scenarios = await Promise.all(
  (await readdir(scenarioDir))
    .filter((f) => f.endsWith(".json"))
    .map(async (f) => JSON.parse(await readFile(new URL(f, scenarioDir)))),
);

const unit = (f) =>
  ({ IDR_T: `Rp${f.value} T`, IDR: `Rp${f.value.toLocaleString("id-ID")}`, persen: `${f.value}%` })[
    f.unit
  ] ?? `${f.value} ${f.unit}`;
const link = (label, url) => (url ? `[${label}](${url})` : label);

const rows = [...budget, ...assumptions, pitch.audience]
  .filter((f) => f.needsReview)
  .map(
    (f) =>
      `- [ ] **${f.label}** (\`${f.key}\`): ${unit(f)}, ${f.kind}, ${link(f.source, f.sourceUrl)}${f.note ? `. ${f.note}` : ""}`,
  );
if (tax.needsReview) {
  rows.push(
    `- [ ] **Aturan pajak ${tax.year}** (\`tax.json\`): brackets, PTKP, biaya jabatan, PPN efektif. Sources: ${tax.sources
      .map((s) => link(s.label, s.url))
      .join("; ")}`,
  );
}
for (const p of provinces.filter((p) => p.needsReview)) {
  rows.push(
    `- [ ] **UMP ${p.name}** (\`provinces.json\`): Rp${p.ump.toLocaleString("id-ID")}, ${link(p.source, p.sourceUrl)}`,
  );
}

for (const sc of scenarios) {
  for (const r of sc.realStory.filter((r) => r.needsReview)) {
    rows.push(`- [ ] **Kisah aslinya (${sc.slug})**: confirm the title of ${link(r.title, r.url)}`);
  }
  for (const a of sc.actions.filter((a) => !a.verifiedAt)) {
    rows.push(
      `- [ ] **Action link (${sc.slug})**: ${link(a.label, a.url)} (${a.org}). Check it is legitimate, then set \`verifiedAt\`.`,
    );
  }
}

const doc = `# Data review checklist

Generated by \`npm run data:review\` from \`src/content/*.json\`. Do not edit by hand.

Each item is shown in the calculator but has not yet been checked against its primary document
(UU APBN 2026 / Nota Keuangan, BPS tables, PMK). To sign one off: check the value, fix it if needed,
remove \`needsReview\` from the JSON, and re-run the script.

**${rows.length} item(s) to review**

${rows.join("\n")}
`;

await mkdir(new URL("../docs/", import.meta.url), { recursive: true });
await writeFile(new URL("../docs/DATA_REVIEW.md", import.meta.url), doc);
console.log(doc);
